{
  home-manager,
  nixgl,
  nixpkgs,
  sops-nix,
  configDirectory,
  secretsFile,
  username,
  homeDirectory,
  stateVersion,
  enableDesktop,
  useNvidiaNixGL,
  gitName,
  email,
  mkPkgs,
  mkQtPackages,
  mkBasePackages,
  mkDesktopPackages,
  mkPackages,
  basePackageSetName,
  desktopPackageSetName,
  packageSetName,
  forAllSystems,
}:
{
  formatter = forAllSystems (system: (mkPkgs system).nixfmt);

  homeConfigurations.${username} = home-manager.lib.homeManagerConfiguration {
    pkgs = mkPkgs "x86_64-linux";
    modules = [
      sops-nix.homeManagerModules.sops
      (
        { config, lib, pkgs, ... }:
        let
          qtPackages = mkQtPackages pkgs;
          qtCmakePrefixPath = pkgs.lib.makeSearchPath "" [
            pkgs.qt6.qtbase
            pkgs.qt6.qtdeclarative
            pkgs.qt6.qtmultimedia
            pkgs.qt6.qtsvg
          ];
          qtPluginPath = pkgs.lib.makeSearchPath "lib/qt-6/plugins" qtPackages;
          qtQmlImportPath = pkgs.lib.makeSearchPath "lib/qt-6/qml" qtPackages;
          isIntelX86Platform = pkgs.stdenv.hostPlatform.system == "x86_64-linux";
          nixglPackages = import nixgl {
            inherit pkgs;
            enable32bits = isIntelX86Platform;
            enableIntelX86Extensions = isIntelX86Platform;
          };
          desktopPackages = mkDesktopPackages "x86_64-linux";
          desktopPackagesWithoutSteam =
            builtins.filter
              (package: lib.getName package != lib.getName pkgs.steam)
              desktopPackages;
        in
        {
          home.username = username;
          home.homeDirectory = homeDirectory;
          home.stateVersion = stateVersion;

          targets.genericLinux.nixGL = {
            packages = nixglPackages;
            defaultWrapper = if useNvidiaNixGL then "nvidia" else "mesa";
            vulkan.enable = true;
          };

          home.packages =
            (mkBasePackages "x86_64-linux")
            ++ lib.optionals enableDesktop (
              desktopPackagesWithoutSteam
              ++ [ (config.lib.nixGL.wrap pkgs.steam) ]
            );

          home.sessionVariables = {
            SHELL = "${pkgs.zsh}/bin/zsh";
            CMAKE_PREFIX_PATH = qtCmakePrefixPath;
            QT_PLUGIN_PATH = qtPluginPath;
            QML2_IMPORT_PATH = qtQmlImportPath;
          } // lib.optionalAttrs enableDesktop {
            TERMINAL = "${pkgs.alacritty}/bin/alacritty";
          };

          systemd.user.startServices = "sd-switch";

          programs.zsh = {
            enable = true;
            oh-my-zsh = {
              enable = true;
              theme = "agnoster";
              plugins = [ "git" ];
            };

            shellAliases = {
              update-system = "NIX_CONFIG_DIR=$HOME/nix-config nix run github:nix-community/home-manager -- switch --impure --flake $HOME/nix-config#$USER";
              wormhole = "wormhole-rs";
              nv = "nvim";
            };

            initContent = ''
              ### DO NOT EDIT THIS FILE MANUALLY. IT IS GENERATED BY HOME MANAGER. YOUR CHANGES WILL BE OVERWRITTEN. PLEASE EDIT YOUR HOME MANAGER CONFIGURATION AND RE-APPLY IT TO MAKE CHANGES TO THIS FILE!!!
              ### set PATH so it includes user's nix bin if it exists
              if [ -d "$HOME/.nix-profile/bin" ] ; then
                  PATH="$HOME/.nix-profile/bin:$PATH"
              fi

              ### set XDG_DATA_DIR so it includes user's nix share if it exists
              if [ -d "$HOME/.nix-profile/share" ] ; then
                  XDG_DATA_DIRS="$HOME/.nix-profile/share:$XDG_DATA_DIRS"
              fi

              export EDITOR="$HOME/.nix-profile/bin/nvim"
              export VISUAL="$HOME/.nix-profile/bin/nvim"
              export SUDO_EDITOR="$HOME/.nix-profile/bin/nvim"
              source $HOME/.local/bin/env
            '';
          };

          programs.alacritty = lib.mkIf enableDesktop {
            enable = true;
            settings = {
              shell.program = "${pkgs.zsh}/bin/zsh";
            };
          };

          programs.git = {
            enable = true;
            settings.user = {
              name = gitName;
              email = email;
            };
          };

          xdg.configFile."git/ignore" = {
            text = ''
              .codex
            '';
            force = true;
          };

          programs.taskwarrior = {
            enable = true;
            package = pkgs.taskwarrior3;
            extraConfig = ''
              uda.reviewed.type=date
              urgency.user.tag.next.coefficient=15
            '';
          };

          home.file.".task/hooks/on-modify.timewarrior" = {
            source = "${pkgs.timewarrior}/share/doc/timew/ext/on-modify.timewarrior";
            executable = true;
          };

          programs.home-manager.enable = true;
        }
      )
    ];
  };

  packages = forAllSystems (
    system:
    let
      pkgs = mkPkgs system;
    in
    {
      default = pkgs.buildEnv {
        name = packageSetName;
        paths = mkPackages system enableDesktop;
      };

      Desktop = pkgs.buildEnv {
        name = desktopPackageSetName;
        paths = (mkBasePackages system) ++ (mkDesktopPackages system);
      };

      base = pkgs.buildEnv {
        name = basePackageSetName;
        paths = mkBasePackages system;
      };
    }
  );

  devShells = forAllSystems (
    system:
    let
      pkgs = mkPkgs system;
      qtCmakePrefixPath = pkgs.lib.makeSearchPath "" [
        pkgs.qt6.qtbase
        pkgs.qt6.qtdeclarative
        pkgs.qt6.qtmultimedia
        pkgs.qt6.qtsvg
      ];
    in
    {
      default = pkgs.mkShell {
        packages = mkPackages system enableDesktop;
        shellHook = ''
          export CMAKE_PREFIX_PATH="${qtCmakePrefixPath}:$CMAKE_PREFIX_PATH"
        '';
      };
    }
  );
}
