{
  home-manager,
  nixpkgs,
  username,
  homeDirectory,
  gitName,
  email,
  mkPkgs,
  mkPackages,
  packageSetName,
  forAllSystems,
}:
{
  formatter = forAllSystems (system: (mkPkgs system).nixfmt);

  homeConfigurations.${username} = home-manager.lib.homeManagerConfiguration {
    pkgs = mkPkgs "x86_64-linux";
    modules = [
      (
        { ... }:
        {
          home.username = username;
          home.homeDirectory = homeDirectory;
          home.stateVersion = "25.05";

          home.packages = mkPackages "x86_64-linux";

          systemd.user.startServices = "sd-switch";

          programs.zsh = {
            enable = true;
            oh-my-zsh = {
              enable = true;
              theme = "agnoster";
              plugins = [ "git" ];
            };

            shellAliases = {
              update-system = "nix run github:nix-community/home-manager -- switch --flake $HOME/nix-config#$USER";
              wormhole = "wormhole-rs";
              nv = "nvim";
            };

            initContent = ''
              ### DO NOT EDIT THIS FILE MANUALLY. IT IS GENERATED BY HOME MANAGER. YOUR CHANGES WILL BE OVERWRITTEN. PLEASE EDIT YOUR HOME MANAGER CONFIGURATION AND RE-APPLY IT TO MAKE CHANGES TO THIS FILE!!!
              ### set PATH so it includes user's nix bin if it exists
              if [ -d "$HOME/.nix-profile/bin" ] ; then
                  PATH="$HOME/.nix-profile/bin:$PATH"
              fi

              ### set XDG_DATA_DIR so it includes user's nix share if it exists
              if [ -d "$HOME/.nix-profile/share" ] ; then
                  XDG_DATA_DIRS="$HOME/.nix-profile/share:$XDG_DATA_DIRS"
              fi

              export EDITOR="$HOME/.nix-profile/bin/nvim"
              export VISUAL="$HOME/.nix-profile/bin/nvim"
              export SUDO_EDITOR="$HOME/.nix-profile/bin/nvim"
            '';
          };

          home.file.".zshrc" = {
            text = "";
            force = true;
          };

          programs.git = {
            enable = true;
            settings.user = {
              name = gitName;
              email = email;
            };
          };

          programs.home-manager.enable = true;
        }
      )
    ];
  };

  packages = forAllSystems (
    system:
    let
      pkgs = mkPkgs system;
    in
    {
      default = pkgs.buildEnv {
        name = packageSetName;
        paths = mkPackages system;
      };
    }
  );

  devShells = forAllSystems (
    system:
    let
      pkgs = mkPkgs system;
    in
    {
      default = pkgs.mkShell {
        packages = mkPackages system;
      };
    }
  );
}
