{
  description = "Reusable home-manager flake built for servers. Includes a set of common tools and packages I use across all my machines, and is designed to unify and simplify configuration management.";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    { home-manager, nixpkgs, ... }:
    let
      #-- USER CONFIGURATION --#
      # CHANGE THESE TO YOUR OWN VALUES BEFORE USING THIS FLAKE
      fullName = "Derek R. Neilson";
      gitName = "dwerkjem";
      email = "derekrneilson@gmail.com";
      username = "derek";
      #-- END OF USER CONFIGURATION--#
      homeDirectory = "/home/${username}";
      packageSetName = "${username}-global-tools";
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
      mkPackages =
        system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
          # Keep Python CLI tooling bundled under one interpreter to avoid
          # Home Manager path collisions between multiple Python versions.
          python313Env = pkgs.python313.withPackages (
            ps: with ps; [
              pip
              virtualenv
              wheel
              setuptools
              black
              isort
            ]
          );
          lazyvimInit = pkgs.writeText "lazyvim-init.lua" ''
            vim.g.mapleader = " "
            vim.g.maplocalleader = "\\"

            vim.opt.rtp:prepend("${pkgs.vimPlugins.lazy-nvim}")

            require("lazy").setup({
              spec = {
                {
                  dir = "${pkgs.vimPlugins.LazyVim}",
                  name = "LazyVim",
                  import = "lazyvim.plugins",
                },
              },
              defaults = {
                lazy = false,
                version = false,
              },
              checker = {
                enabled = false,
              },
              change_detection = {
                notify = false,
              },
            })
          '';
          # Package the LazyVim config as a normal Neovim binary so it can live
          # in home.packages like the rest of the toolchain.
          lazyvim = pkgs.wrapNeovim pkgs.neovim-unwrapped {
            viAlias = true;
            vimAlias = true;
            configure = {
              customRC = ''
                luafile ${lazyvimInit}
              '';
            };
          };
        in
        with pkgs;
        [
          # General packages and tools
          fd
          git
          nixfmt
          ripgrep
          zsh
          magic-wormhole-rs
          direnv
          postgresql_18
          lazyvim
          nodejs
          nodenv
          python313Env
          poetry
        ];
    in
    {
      formatter = forAllSystems (system: nixpkgs.legacyPackages.${system}.nixfmt);

      homeConfigurations.${username} = home-manager.lib.homeManagerConfiguration {
        pkgs = nixpkgs.legacyPackages.x86_64-linux;
        modules = [
          {
            home.username = username;
            home.homeDirectory = homeDirectory;
            home.stateVersion = "25.05";

            home.packages = mkPackages "x86_64-linux";

            programs.zsh = {
              enable = true;
              oh-my-zsh = {
                enable = true;
                theme = "agnoster";
                plugins = [ "git" ];
              };

              shellAliases = {
                update-system="nix run github:nix-community/home-manager -- switch --flake $HOME/nix-config#$USER";
                wormhole="wormhole-rs";
                nv="nvim";
                };

              initContent = ''
                ### DO NOT EDIT THIS FILE MANUALLY. IT IS GENERATED BY HOME MANAGER. YOUR CHANGES WILL BE OVERWRITTEN. PLEASE EDIT YOUR HOME MANAGER CONFIGURATION AND RE-APPLY IT TO MAKE CHANGES TO THIS FILE!!!
                ### set PATH so it includes user's nix bin if it exists
                if [ -d "$HOME/.nix-profile/bin" ] ; then
                    PATH="$HOME/.nix-profile/bin:$PATH"
                fi

                ### set XDG_DATA_DIR so it includes user's nix share if it exists
                if [ -d "$HOME/.nix-profile/share" ] ; then
                    XDG_DATA_DIRS="$HOME/.nix-profile/share:$XDG_DATA_DIRS"
                fi

                export EDITOR="$HOME/.nix-profile/bin/nvim"
                export VISUAL="$HOME/.nix-profile/bin/nvim"
                export SUDO_EDITOR="$HOME/.nix-profile/bin/nvim"
              '';
            };

            home.file.".zshrc" = {
              text = "";
              force = true;
            };

            programs.git = {
              enable = true;
              settings.user = {
                name = gitName;
                email = email;
              };
            };

            programs.home-manager.enable = true;
          }
        ];
      };

      packages = forAllSystems (
        system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
        in
        {
          default = pkgs.buildEnv {
            name = packageSetName;
            paths = mkPackages system;
          };
        }
      );

      devShells = forAllSystems (
        system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
        in
        {
          default = pkgs.mkShell {
            packages = mkPackages system;
          };
        }
      );
    };
}
